DELETE * FROM EXCHANGE_CURRENCY ;
INSERT INTO EXCHANGE_CURRENCY  (ID , 	FROMCUR  , 	TOCUR ,	RATE  ) VALUES (1,'USD','EPD',10.25);
INSERT INTO EXCHANGE_CURRENCY  (ID , 	FROMCUR  , 	TOCUR ,	RATE  ) VALUES (2,'USD','EUR',2.25);
INSERT INTO EXCHANGE_CURRENCY  (ID , 	FROMCUR  , 	TOCUR ,	RATE  ) VALUES (3,'EUR','USD',15);
INSERT INTO EXCHANGE_CURRENCY  (ID , 	FROMCUR  , 	TOCUR ,	RATE  ) VALUES (4,'EPD','EPD',3);